In [55]:
# Advance Python - 10 Jan 2025
# Data Science
# Numpy Part - 1
 
# What is data science?
# Data science is the study of data to extract meaningful insights for business. 
# It is a multidisciplinary approach that combines principles and practices from the 
# fields of mathematics, statistics, artificial intelligence, and computer engineering 
# to analyze large amounts of data. This analysis helps data scientists to ask and answer questions
# like what happened, why it happened, what will happen, and what can be done with the results.
 
 
# Data Science is about data gathering, analysis and decision-making.
 
# Data Science is about finding patterns in data, through analysis, and make future predictions.
 
# By using Data Science, companies are able to make:
#    Better decisions (should we choose A or B)
#    Predictive analysis (what will happen next?)
#    Pattern discoveries (find pattern, or maybe hidden information in the data)
 
# Where is Data Science Needed?
 
# Data Science is used in many industries in the world today, e.g. banking,
# consultancy, healthcare, and manufacturing.

In [56]:
# Numpy
 
# NumPy is a Python library used for working with arrays.
 
# It also has functions for working in domain of linear algebra, fourier transform,
# and matrices.
 
# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you
# can use it freely.
 
# NumPy stands for Numerical Python.

In [57]:
import numpy as np

list1 = [1, 2, 3, 4, 5]
print(list1 * 2)

for i in list1:
    print(i * 2)




[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
2
4
6
8
10


In [58]:
arr = np.array([1, 2, 3, 4, 5])
print(arr * 2)


[ 2  4  6  8 10]


In [59]:
# array is a collection of similar data type elements.
arr = np.array([1, 2, 3,'Python', True, 3.14])
print(arr)


['1' '2' '3' 'Python' 'True' '3.14']


In [60]:
# Numpy Array()
arr = np.array([1, 2, 3,'Python', True, 3.14])
print(arr)


['1' '2' '3' 'Python' 'True' '3.14']


In [61]:
# shape Property
# The shape property is used to dimensions of an array.

# for 1D array shape return (n,)
# where n is the number of elements 

# for 1D array shape return (n,m)
# where n is the number of rows and m is the number of columns

print(arr.shape)

(6,)


In [62]:
# Indexing and slicing

arr = np.array([1, 2, 3, 4, 5])

# 1  2  3  4  5
# 0  1  2  3  4
# -5 -4 -3 -2 -1


print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:4])
print(arr[1:])
print(arr[:])
print(arr[::2])

1
5
[2 3 4]
[1 2 3 4]
[2 3 4 5]
[1 2 3 4 5]
[1 3 5]


In [63]:
# 2D Array
twod = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(twod)
print(twod.shape)


# 3 X 4 matrix

threed = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(threed)
print(threed.shape)


# 5 x 2 matirx

fivex2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(fivex2)
print(fivex2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)


In [64]:
# Indexing in 2D array

twod = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(twod)
print(twod[0, 2])
# print second row 
print(twod[1,:])

# print second column
print(twod[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[4 5 6]
[2 5 8]


In [65]:
# dtype property
# The dtype property is used to return the data type of the array elements.

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
print(arr.itemsize)  # int64 : memory size of one array element is 8 bytes

# int64 : memory size of one array element is bits.  [8 bytes]

arr = np.array([1, 2, 3, 4, 5], dtype='i2')
print(arr.itemsize, 'bytes') #2 bytes --> 16 bits

arr = np.array([1, 2, 3, 4, 5], dtype='i4')
print(arr.itemsize, 'bytes') #4 bytes --> 32 bits


int64
8
2 bytes
4 bytes


In [66]:
# copy() vs view()

#in copy() if you make any changes in org array, it won't reflect in copied array
#in view() if you make any changes in copy array, it will reflect in orginal array

org_arr = np.array([10, 20, 30, 40, 50])
print(org_arr)

copied_arr = org_arr.copy()
print(copied_arr)

copied_arr[0] = 100
print(copied_arr)
print(org_arr)

[10 20 30 40 50]
[10 20 30 40 50]
[100  20  30  40  50]
[10 20 30 40 50]


In [67]:
# view() if you make any changes in copy array, it will reflect in orginal array

org_arr = np.array([10, 20, 30, 40, 50])
print(org_arr)

copied_arr = org_arr.view()
print(copied_arr)

copied_arr[0] = 100
print(copied_arr)
print(org_arr)

[10 20 30 40 50]
[10 20 30 40 50]
[100  20  30  40  50]
[100  20  30  40  50]


In [68]:
# reshape() : used to change the dimensions of an array
# 1d --> 2d or 2d --> 1d

# covert 1d into 2d 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.shape)  # 12 --> 2x6, 3x4, 4x3, 6x2, 12x1

arr = arr.reshape(2, 6)
print(arr)


(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [69]:
# covert 2d into 1d

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)  # 3x3


arr = arr.reshape(9)
print(arr)

(3, 3)
[1 2 3 4 5 6 7 8 9]


In [70]:
#  another way to covert 2d into 1d

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)  # 3x3


arr = arr.reshape(-1)
print(arr)

(3, 3)
[1 2 3 4 5 6 7 8 9]


In [71]:
#  another way to covert 2d into 1d

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)  # 3x3


arr = arr.flatten()
print(arr)

(3, 3)
[1 2 3 4 5 6 7 8 9]


In [72]:
# Fliter an array 
arr = np.array([23, 12, 14, 54, 34, 89, 6])
op = arr%2 == 0
print(op) # Boolean Masking 
print(arr[op])

[False  True  True  True  True False  True]
[12 14 54 34  6]


In [73]:
arr = np.array([23, 12, 14, 54, 34, 89, 6])
res = arr > 5
print(arr[res])

[23 12 14 54 34 89  6]


In [74]:
arr = np.array([23, 12, 14, 54, 34, 89, 6])
res = (arr > 5) & (arr < 50)
print(arr[res])

[23 12 14 34  6]


In [75]:
# Modify element using boolen indexing
arr = np.array([12,3,4,5,32,67,52,25,50])
arr[arr%2 == 0] = 0
print(arr)

[ 0  3  0  5  0 67  0 25  0]


In [76]:
# where() : used to return the index of the elements where the condition is True
arr = np.array([1,4,2,7,8,3,9,10,2,4])  

res = np.where(arr>5)
print(res)
print(arr[res])

(array([3, 4, 6, 7]),)
[ 7  8  9 10]


In [77]:
# concantenate() : used to join two or more arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [78]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [79]:
# array_split(arrayName, splitValue) : used to split an array into multiple sub-arrays

arr = np.array([1, 2, 3, 4, 5, 6, 7])
res = np.array_split(arr, 3)
print(res)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [80]:
# sorting of an array
# sort() : used to sort an array

arr = np.array([23, 12, 14, 54, 34, 89, 6])
print(np.sort(arr))  # by default ascending order

[ 6 12 14 23 34 54 89]


In [81]:
arr = np.array([23, 12, 14, 54, 34, 89, 6])
print(np.sort(arr)[::-1])  # by default descending order

[89 54 34 23 14 12  6]


In [82]:
# zeros() ones() full() sum() 

# zeros() : used to create an array with zeros
# defualt data type is float

#Id 
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [83]:
arr = np.zeros(5, dtype='i')
print(arr)

[0 0 0 0 0]


In [84]:
arr = np.zeros((2, 3), dtype = 'i')
print(arr)

[[0 0 0]
 [0 0 0]]


In [85]:
# full() : used to create an array with a specified value

x = np.full(5, 3)
print(x)

[3 3 3 3 3]


In [86]:
x = np.full((5, 3), 26 )
print(x)

[[26 26 26]
 [26 26 26]
 [26 26 26]
 [26 26 26]
 [26 26 26]]


In [87]:
# sum() : used to calculate the sum of the elements in an array

print(x.sum())


390


In [88]:
# Numpy Random Module
from numpy import random

x = random.randint(100) # random number between 0 to 100
print(x)

43


In [89]:
x = random.randint(120, 150)
print(x)

130


In [90]:
# rand() method generate a random float number between 0 and 1

x = random.rand()
print(x)

0.13664281792830923


In [91]:
# 1d

x = random.randint(100, size=(5))
print(x)


[37 34 15 14 66]


In [92]:
# 2d

x = random.randint(10, 40, size=(5,4))
print(x)


[[32 31 21 15]
 [19 31 23 37]
 [19 31 18 31]
 [11 12 23 14]
 [20 29 38 21]]


In [93]:
# numpy arange()
# arange() : used to generate a sequence of numbers

x = np.arange(50)
print(x)


# numpy arange(x,y)
# arange() : used to generate a sequence of numbers (between range x to y)

y = np.arange(20,30)
print(y)

# numpy arange(x,y, stepcount)
# arange() : used to generate a sequence of numbers (between range x to y and also stepcount)

y = np.arange(20,30,2)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[20 21 22 23 24 25 26 27 28 29]
[20 22 24 26 28]


In [94]:
# numpy Broadcasting

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
print(arr1 + arr2)

[11 22 33 44 55]


In [95]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2])
print(arr1 + arr2)

[3 4 5 6 7]
