In [30]:
# Advance Python - 10 Jan 2025
# Data Science
# Numpy Part - 1
 
# What is data science?
# Data science is the study of data to extract meaningful insights for business. 
# It is a multidisciplinary approach that combines principles and practices from the 
# fields of mathematics, statistics, artificial intelligence, and computer engineering 
# to analyze large amounts of data. This analysis helps data scientists to ask and answer questions
# like what happened, why it happened, what will happen, and what can be done with the results.
 
 
# Data Science is about data gathering, analysis and decision-making.
 
# Data Science is about finding patterns in data, through analysis, and make future predictions.
 
# By using Data Science, companies are able to make:
#    Better decisions (should we choose A or B)
#    Predictive analysis (what will happen next?)
#    Pattern discoveries (find pattern, or maybe hidden information in the data)
 
# Where is Data Science Needed?
 
# Data Science is used in many industries in the world today, e.g. banking,
# consultancy, healthcare, and manufacturing.

In [31]:
# Numpy
 
# NumPy is a Python library used for working with arrays.
 
# It also has functions for working in domain of linear algebra, fourier transform,
# and matrices.
 
# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you
# can use it freely.
 
# NumPy stands for Numerical Python.

In [32]:
import numpy as np

list1 = [1, 2, 3, 4, 5]
print(list1 * 2)

for i in list1:
    print(i * 2)




[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
2
4
6
8
10


In [33]:
arr = np.array([1, 2, 3, 4, 5])
print(arr * 2)


[ 2  4  6  8 10]


In [34]:
# array is a collection of similar data type elements.
arr = np.array([1, 2, 3,'Python', True, 3.14])
print(arr)


['1' '2' '3' 'Python' 'True' '3.14']


In [35]:
# Numpy Array()
arr = np.array([1, 2, 3,'Python', True, 3.14])
print(arr)


['1' '2' '3' 'Python' 'True' '3.14']


In [36]:
# shape Property
# The shape property is used to dimensions of an array.

# for 1D array shape return (n,)
# where n is the number of elements 

# for 1D array shape return (n,m)
# where n is the number of rows and m is the number of columns

print(arr.shape)

(6,)


In [37]:
# Indexing and slicing

arr = np.array([1, 2, 3, 4, 5])

# 1  2  3  4  5
# 0  1  2  3  4
# -5 -4 -3 -2 -1


print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:4])
print(arr[1:])
print(arr[:])
print(arr[::2])

1
5
[2 3 4]
[1 2 3 4]
[2 3 4 5]
[1 2 3 4 5]
[1 3 5]


In [38]:
# 2D Array
twod = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(twod)
print(twod.shape)


# 3 X 4 matrix

threed = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(threed)
print(threed.shape)


# 5 x 2 matirx

fivex2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(fivex2)
print(fivex2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)


In [39]:
# Indexing in 2D array

twod = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(twod)
print(twod[0, 2])
# print second row 
print(twod[1,:])

# print second column
print(twod[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[4 5 6]
[2 5 8]


In [40]:
# dtype property
# The dtype property is used to return the data type of the array elements.

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
print(arr.itemsize)  # int64 : memory size of one array element is 8 bytes

# int64 : memory size of one array element is bits.  [8 bytes]

arr = np.array([1, 2, 3, 4, 5], dtype='i2')
print(arr.itemsize, 'bytes') #2 bytes --> 16 bits

arr = np.array([1, 2, 3, 4, 5], dtype='i4')
print(arr.itemsize, 'bytes') #4 bytes --> 32 bits


int64
8
2 bytes
4 bytes
